[package]
name = "merkle-sum-sparse-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.217", features = ["derive", "rc"] }
sha2 = "0.10.8"
typenum = "1.17.0"
serde_with = "3.0"

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
